version: "3"
services:
  web:
    image: nginx
    networks:
      - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.secret:/etc/certs
     - ../javaman-client/build:/etc/nginx/html
    ports:
     - "443:443"
  redis:
    image: redis:alpine
    networks:
      - network
  api:
    build: .
    env_file: ~/.secret/secrets.env
    ports:
     - "3000:3000"
    networks:
      - network
networks:
  network:
